# Generated by Django 6.1.1 on 2026-09-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('incompleted', 'Incompleted')], default='pending', max_length=20),
        ),
    ]
